spring:
  application:
    name: bush_cinema
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  h2:
    console:
      enabled: true
      path: /h2-console

springdoc:
  swagger-ui:
    operationsSorter: method     # или alpha, method, none
    tagsSorter: alpha            # или alpha, none
